language: go
install:
 - go get github.com/cxfksword/gopacket
 - go get github.com/cxfksword/gopacket/layers
 - go get github.com/cxfksword/gopacket/tcpassembly
script:
 - go test github.com/cxfksword/gopacket
 - go test github.com/cxfksword/gopacket/layers
 - go test github.com/cxfksword/gopacket/tcpassembly
 - ./.travis.gofmt.sh
